const data = [
    {
        id: 1,
        title: "Scientists speculate that ours might not be held",
        img: "blog01.jpg",
        group: "blog",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 2,
        title: "The Multiverse is the collection of alternate universes",
        img: "blog02.jpg",
        group: "blog",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 3,
        title: "That share a universal hierarchy a large variety of these",
        img: "blog03.jpg",
        group: "blog",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 4,
        title: "Universes were originated from another due to a major",
        img: "blog04.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 5,
        title: "A hypothetical collection of potentially diverse",
        img: "blog05.jpg",
        group: "blog",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 6,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "blog06.jpg",
        group: "blog",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 7,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog07.jpg",
        group: "blog",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 8,
        title: "Observable universes each of which would comprise",
        img: "blog08.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 9,
        title: "A hypothetical collection of potentially diverse",
        img: "blog09.jpg",
        group: "blog",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 10,
        title: "Experimentally accessible by a connected community",
        img: "blog10.jpg",
        group: "blog",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 11,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "blog11.jpg",
        group: "blog",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 12,
        title: "Observable universes each of which would comprise",
        img: "blog12.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 13,
        title: "Of observers the observable known universe",
        img: "blog13.jpg",
        group: "blog",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 14,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog14.jpg",
        group: "blog",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 15,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog15.jpg",
        group: "blog",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 16,
        title: "Observable universes each of which would comprise",
        img: "blog16.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 17,
        title: "Scientists speculate that ours might not be held",
        img: "blog17.jpg",
        group: "blog",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 18,
        title: "The Multiverse is the collection of alternate universes",
        img: "blog18.jpg",
        group: "blog",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 19,
        title: "That share a universal hierarchy a large variety of these",
        img: "blog19.jpg",
        group: "blog",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 20,
        title: "Universes were originated from another due to a major",
        img: "blog20.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 21,
        title: "A hypothetical collection of potentially diverse",
        img: "blog21.jpg",
        group: "blog",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 22,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "blog22.jpg",
        group: "blog",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 23,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "blog23.jpg",
        group: "blog",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 24,
        title: "Observable universes each of which would comprise",
        img: "blog24.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 25,
        title: "Scientists speculate that ours might not be held",
        img: "blog25.jpg",
        group: "blog",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 26,
        title: "The Multiverse is the collection of alternate universes",
        img: "blog26.jpg",
        group: "blog",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 27,
        title: "That share a universal hierarchy a large variety of these",
        img: "blog27.jpg",
        group: "blog",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 28,
        title: "Universes were originated from another due to a major",
        img: "blog28.jpg",
        group: "blog",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 29,
        title: "A hypothetical collection of potentially diverse",
        img: "blog29.jpg",
        group: "blog",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 30,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "blog30.jpg",
        group: "blog",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 31,
        title: "Practical steps to build transparency in your remote business",
        img: "interior_01.jpg",
        group: "interior",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 32,
        title: "Why we need guidelines for brain scan data to real data.",
        img: "interior_02.jpg",
        group: "interior",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 33,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "interior_03.jpg",
        group: "interior",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 34,
        title: "Observable universes each of which would comprise",
        img: "interior_04.jpg",
        group: "interior",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 35,
        title: "Scientists speculate that ours might not be held",
        img: "interior_05.jpg",
        group: "interior",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 36,
        title: "The Multiverse is the collection of alternate universes",
        img: "interior_06.jpg",
        group: "interior",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 37,
        title: "That share a universal hierarchy a large variety of these",
        img: "interior_07.jpg",
        group: "interior",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 38,
        title: "Universes were originated from another due to a major",
        img: "interior_08.jpg",
        group: "interior",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 39,
        title: "A hypothetical collection of potentially diverse",
        img: "interior_09.jpg",
        group: "interior",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 40,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "interior_30.jpg",
        group: "interior",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 41,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "interior_11.jpg",
        group: "interior",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 42,
        title: "Observable universes each of which would comprise",
        img: "interior_12.jpg",
        group: "interior",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 43,
        title: "Of observers the observable known universe",
        img: "interior_13.jpg",
        group: "interior",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 44,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "interior_14.jpg",
        group: "interior",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 45,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "interior_15.jpg",
        group: "interior",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 46,
        title: "Observable universes each of which would comprise",
        img: "interior_16.jpg",
        group: "interior",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 47,
        title: "Scientists speculate that ours might not be held",
        img: "interior_17.jpg",
        group: "interior",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 48,
        title: "The Multiverse is the collection of alternate universes",
        img: "interior_18.jpg",
        group: "interior",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 49,
        title: "That share a universal hierarchy a large variety of these",
        img: "interior_19.jpg",
        group: "interior",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 50,
        title: "Universes were originated from another due to a major",
        img: "interior_20.jpg",
        group: "interior",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 51,
        title: "Scientists speculate that ours might not be held",
        img: "travel_01.jpg",
        group: "travel",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 52,
        title: "The Multiverse is the collection of alternate universes",
        img: "travel_02.jpg",
        group: "travel",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 53,
        title: "That share a universal hierarchy a large variety of these",
        img: "travel_03.jpg",
        group: "travel",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 54,
        title: "Universes were originated from another due to a major",
        img: "travel_04.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 55,
        title: "A hypothetical collection of potentially diverse",
        img: "travel_05.jpg",
        group: "travel",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 56,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "travel_06.jpg",
        group: "travel",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 57,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "travel_07.jpg",
        group: "travel",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 58,
        title: "Observable universes each of which would comprise",
        img: "travel_08.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 59,
        title: "A hypothetical collection of potentially diverse",
        img: "travel_09.jpg",
        group: "travel",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 60,
        title: "Experimentally accessible by a connected community",
        img: "travel_10.jpg",
        group: "travel",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 61,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "travel_11.jpg",
        group: "travel",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 62,
        title: "Observable universes each of which would comprise",
        img: "travel_12.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 63,
        title: "Of observers the observable known universe",
        img: "travel_13.jpg",
        group: "travel",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 64,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "travel_14.jpg",
        group: "travel",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 65,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "travel_15.jpg",
        group: "travel",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 66,
        title: "Observable universes each of which would comprise",
        img: "travel_16.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 67,
        title: "Scientists speculate that ours might not be held",
        img: "travel_17.jpg",
        group: "travel",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 68,
        title: "The Multiverse is the collection of alternate universes",
        img: "travel_18.jpg",
        group: "travel",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 69,
        title: "That share a universal hierarchy a large variety of these",
        img: "travel_19.jpg",
        group: "travel",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 70,
        title: "Universes were originated from another due to a major",
        img: "travel_20.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 71,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "travel_21.jpg",
        group: "travel",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 72,
        title: "Scientists speculate that ours might not be held",
        img: "tech_01.jpg",
        group: "technology",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 73,
        title: "The Multiverse is the collection of alternate universes",
        img: "tech_02.jpg",
        group: "technology",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 74,
        title: "That share a universal hierarchy a large variety of these",
        img: "tech_03.jpg",
        group: "technology",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 75,
        title: "Universes were originated from another due to a major",
        img: "tech_04.jpg",
        group: "technology",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 76,
        title: "A hypothetical collection of potentially diverse",
        img: "tech_05.jpg",
        group: "technology",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 77,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "tech_06.jpg",
        group: "technology",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 78,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "tech_07.jpg",
        group: "technology",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 79,
        title: "Scientists speculate that ours might not be held",
        img: "nft_blog01.jpg",
        group: "nft",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 80,
        title: "The Multiverse is the collection of alternate universes",
        img: "nft_blog02.jpg",
        group: "nft",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 81,
        title: "That share a universal hierarchy a large variety of these",
        img: "nft_blog03.jpg",
        group: "nft",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 82,
        title: "Universes were originated from another due to a major",
        img: "nft_blog04.jpg",
        group: "nft",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 83,
        title: "A hypothetical collection of potentially diverse",
        img: "nft_blog05.jpg",
        group: "nft",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 84,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "nft_blog06.jpg",
        group: "nft",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 85,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "nft_blog07.jpg",
        group: "nft",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 86,
        title: "Observable universes each of which would comprise",
        img: "nft_blog08.jpg",
        group: "nft",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 87,
        title: "A hypothetical collection of potentially diverse",
        img: "nft_blog09.jpg",
        group: "nft",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 88,
        title: "Experimentally accessible by a connected community",
        img: "nft_blog10.jpg",
        group: "nft",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 89,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "nft_blog11.jpg",
        group: "nft",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 90,
        title: "Observable universes each of which would comprise",
        img: "nft_blog12.jpg",
        group: "nft",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 91,
        title: "Of observers the observable known universe",
        img: "nft_blog13.jpg",
        group: "nft",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 92,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "nft_blog14.jpg",
        group: "nft",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 93,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "nft_blog15.jpg",
        group: "nft",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 94,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "nft_slider01.jpg",
        group: "nft",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 95,
        title: "Observable universes each of which would comprise",
        img: "nft_slider02.jpg",
        group: "nft",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 96,
        title: "Of observers the observable known universe",
        img: "nft_slider03.jpg",
        group: "nft",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 97,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "nft_slider04.jpg",
        group: "nft",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 98,
        title: "Scientists speculate that ours might not be held",
        img: "life_style01.jpg",
        group: "lifestyle",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 99,
        title: "The Multiverse is the collection of alternate universes",
        img: "life_style02.jpg",
        group: "lifestyle",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 100,
        title: "That share a universal hierarchy a large variety of these",
        img: "life_style03.jpg",
        group: "lifestyle",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 101,
        title: "Universes were originated from another due to a major",
        img: "life_style04.jpg",
        group: "lifestyle",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 102,
        title: "A hypothetical collection of potentially diverse",
        img: "life_style05.jpg",
        group: "lifestyle",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 103,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "life_style06.jpg",
        group: "lifestyle",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 104,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "life_style07.jpg",
        group: "lifestyle",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 105,
        title: "Observable universes each of which would comprise",
        img: "life_style08.jpg",
        group: "lifestyle",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 106,
        title: "A hypothetical collection of potentially diverse",
        img: "life_style09.jpg",
        group: "lifestyle",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 107,
        title: "Experimentally accessible by a connected community",
        img: "life_style10.jpg",
        group: "lifestyle",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 108,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "life_style11.jpg",
        group: "lifestyle",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 109,
        title: "Observable universes each of which would comprise",
        img: "life_style12.jpg",
        group: "lifestyle",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 110,
        title: "Of observers the observable known universe",
        img: "life_style13.jpg",
        group: "lifestyle",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 111,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "life_style14.jpg",
        group: "lifestyle",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 112,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "life_style15.jpg",
        group: "lifestyle",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 113,
        title: "Observable universes each of which would comprise",
        img: "life_style16.jpg",
        group: "lifestyle",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 114,
        title: "Scientists speculate that ours might not be held",
        img: "life_style17.jpg",
        group: "lifestyle",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 115,
        title: "Scientists speculate that ours might not be held",
        img: "minimal_post01.jpg",
        group: "minimal",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 116,
        title: "The Multiverse is the collection of alternate universes",
        img: "minimal_post02.jpg",
        group: "minimal",
        trending: false,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 117,
        title: "That share a universal hierarchy a large variety of these",
        img: "minimal_post03.jpg",
        group: "minimal",
        trending: false,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 118,
        title: "Universes were originated from another due to a major",
        img: "minimal_post04.jpg",
        group: "minimal",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 119,
        title: "A hypothetical collection of potentially diverse",
        img: "minimal_post05.jpg",
        group: "minimal",
        trending: false,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 120,
        title: "Stanford physicists Andrei Linde In a new study",
        img: "minimal_post06.jpg",
        group: "minimal",
        trending: true,
        category: "Tech",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 121,
        title: "Accessible to telescopes, is about 90 billion years",
        img: "minimal_post07.jpg",
        group: "minimal",
        trending: true,
        category: "Movie",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 122,
        title: "Observable universes each of which would comprise",
        img: "minimal_post08.jpg",
        group: "minimal",
        trending: true,
        category: "Sports",
        author: "miranda h.",
        date: "25 April 2022",
    },
    {
        id: 123,
        title: "A hypothetical collection of potentially diverse",
        img: "minimal_post09.jpg",
        group: "minimal",
        trending: true,
        category: "Gaming",
        author: "miranda h.",
        date: "25 April 2022",
    },
]
export default data